### ISSUE TITLE
example site

### ISSUE THREAD

**Issue by bowman2001** [bowman2001/perplex#108]
Create an example site as it is custom for Hugo themes on the Hugo themes page

**Comment by janvanveldhuizen** [comment]
I tried the example site to use it as starting point for my own site.
When I clone the entire perplex repo and I cd into the exampleSite directory, then `hugo serve` works and renders the example site.
Then I take the contents of that directory, copy it to a new directory:
`mkdir ~/test`
`cp ~/dev/perplex/exampleSite/* -R ~/test`
`cd ~/test`
`hugo serve`

Then it says:
```
Error: command error: failed to load modules: failed to download modules: failed to execute 'go [mod download -modcacherw]': failed to execute binary "go" with args [mod download -modcacherw]: go: github.com/bowman2001/perplex@v0.19.8 (replaced by ../): reading ../go.mod: open /home/papasmurf/go.mod: no such file or directory
 *errors.errorString
```

What have I done wrong? 
Isn't it a good approach to take a copy of the example site as a starting point?

I think the problem is that `replace` line in `go.mod`.
The thing is, I worked with Hugo before, but never used the concept of modules....
